# K-means x Hierárquico x DBSCAN

In [56]:
# Importações para a comparativo

from sklearn import datasets
import numpy as np
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN

In [57]:
# Importando um dataset existente no sklearn

X_random, y_random = datasets.make_moons(n_samples=1500, noise = 0.09)

In [58]:
# Verificando as variáveis

X_random, y_random

(array([[ 1.89012253, -0.05881601],
        [ 0.14490063,  0.01808423],
        [ 1.89453158,  0.22592525],
        ...,
        [ 0.20506178,  0.18937848],
        [ 1.96553265, -0.03678115],
        [-0.52736337,  1.00341013]]),
 array([1, 1, 1, ..., 1, 1, 0]))

In [59]:
# Verifincando possíveis resultados

np.unique(y_random)

array([0, 1])

In [60]:
# Vendo como o gráfico está distribuído

grafico = px.scatter(x = X_random[:,0], y = X_random[:,1])
grafico.show()

In [61]:
# Fazendo agrupamento usando KMeans

kmeans = KMeans(n_clusters=2, n_init=10)
rotulos = kmeans.fit_predict(X_random)
grafico = px.scatter(x = X_random[:,0], y = X_random[:, 1], color = rotulos)
grafico.show()

# kmeans 'dividiu' os registros ao meio, não sendo interessante

In [62]:
# Fazendo agrupamento usando Agglomerative Clustering

hc = AgglomerativeClustering(n_clusters=2, metric='euclidean', linkage='ward')
rotulos = hc.fit_predict(X_random)
grafico = px.scatter(x = X_random[:,0], y = X_random[:, 1], color = rotulos)
grafico.show()

# agrupamento hierárquico conseguiu dividir uma parte perfeitamente, mas outra parte não foi tão boa

In [63]:
# Fazendo agrupamento usando DBSCAN

dbscan = DBSCAN(eps=0.1)
rotulos = dbscan.fit_predict(X_random)
grafico = px.scatter(x = X_random[:,0], y = X_random[:, 1], color = rotulos)
grafico.show()

# nesse caso conseguiu ser dividido de melhor forma
# tudo depende da base de dados e testes