# Redes neurais artificiais

# Base de plano de saúde

In [47]:
# Importações

import pickle
import plotly.express as px

from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

In [48]:
# Fazendo upload das variáveis

with open('/content/drive/MyDrive/variaveis treino/saude.pkl', 'rb') as f:
    x_plano_saude, y_plano_saude = pickle.load(f)

In [49]:
# Fazendo o shape delas

x_plano_saude.shape, y_plano_saude.shape

((10, 1), (10,))

In [50]:
# Fazendo a padronização

scaler_x_saude = StandardScaler()
scaler_y_saude = StandardScaler()

x_plano_saude_scaled = scaler_x_saude.fit_transform(x_plano_saude)
y_plano_saude_scaled = scaler_y_saude.fit_transform(y_plano_saude.reshape(-1, 1))

In [51]:
x_plano_saude_scaled.shape, y_plano_saude_scaled.shape

((10, 1), (10, 1))

In [52]:
# Criando rede neural e fazendo o treinamento

regressor_rna_saude = MLPRegressor(max_iter=1000)
regressor_rna_saude.fit(x_plano_saude_scaled, y_plano_saude_scaled.ravel())

MLPRegressor(max_iter=1000)

In [53]:
# Visualizando o score

regressor_rna_saude.score(x_plano_saude_scaled, y_plano_saude_scaled)

0.960548451490352

In [54]:
# Visualizando o gráfico

grafico = px.scatter(x = x_plano_saude_scaled.ravel(), y = y_plano_saude_scaled.ravel())
grafico.add_scatter(x= x_plano_saude_scaled.ravel(), y = regressor_rna_saude.predict(x_plano_saude_scaled), name = 'Regressão')
grafico.show()

In [55]:
novo = [[40]]
novo = scaler_x_saude.transform(novo)
novo

array([[-0.03481553]])

In [56]:
scaler_y_saude.inverse_transform(regressor_rna_saude.predict(novo).reshape(-1, 1))

array([[1137.48968609]])

# Base de preço das casas

In [57]:
# Fazendo o upload das variáveis de teste e treinamento

with open('/content/drive/MyDrive/variaveis treino/casas.pkl', 'rb') as f:
    x_casas_treinamento, y_casas_treinamento, x_casas_teste, y_casas_teste = pickle.load(f)

In [58]:
print(f'O tamanho das variáveis de treinamento é  de: {x_casas_treinamento.shape, y_casas_treinamento.shape}')
print(f'O tamamho das variáves de teste é de: {x_casas_teste.shape, y_casas_teste.shape}')

O tamanho das variáveis de treinamento é  de: ((15129, 16), (15129,))
O tamamho das variáves de teste é de: ((6484, 16), (6484,))


In [59]:
# Fazendo a padronização

scaler_x_casas = StandardScaler()
scaler_y_casas = StandardScaler()

x_casas_treinamento_scaled = scaler_x_casas.fit_transform(x_casas_treinamento)
x_casas_teste_scaled = scaler_x_casas.fit_transform(x_casas_teste)

y_casas_treinamento_scaled = scaler_y_casas.fit_transform(y_casas_treinamento.to_numpy().reshape(-1, 1))
y_casas_teste_scaled = scaler_y_casas.fit_transform(y_casas_teste.to_numpy().reshape(-1, 1))

In [60]:
print(f'O tamanho das variáeis de treino padronizada é: {x_casas_treinamento_scaled.shape, y_casas_treinamento_scaled.shape}')
print(f'O tamanho das variáveis de teste padronizada é: {x_casas_teste_scaled.shape, y_casas_teste_scaled.shape}')

O tamanho das variáeis de treino padronizada é: ((15129, 16), (15129, 1))
O tamanho das variáveis de teste padronizada é: ((6484, 16), (6484, 1))


In [61]:
# Criando rede neural e fazendo o treinamento

regressor_rna_casas = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9, 9))
regressor_rna_casas.fit(x_casas_treinamento_scaled, y_casas_treinamento_scaled.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [62]:
# Vendo o score na base de treinamento

regressor_rna_casas.score(x_casas_treinamento_scaled, y_casas_treinamento_scaled)

0.8954151714009838

In [63]:
# Vendo o score na base de teste

regressor_rna_casas.score(x_casas_teste_scaled, y_casas_teste_scaled)

0.8768895462059576

In [64]:
# Fazendo previsões e vendo a média de erro

previsoes = regressor_rna_casas.predict(x_casas_teste_scaled)
previsoes

array([-0.62125735,  2.94102001,  0.06872381, ..., -0.41187846,
       -0.82185265, -0.89279889])

In [65]:
# Voltando as variáveis ao normal

y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes.reshape(-1, 1))

In [66]:
# Média de erro absoluta

print(f'A margem de erro é de: {mean_absolute_error(y_casas_teste_inverse, previsoes_inverse)}')

A margem de erro é de: 76314.26964329241
